[workspace]
members = [
    "demo/cli_csv",
    "notes/*",
]
resolver = "3"

[workspace.dependencies]
num_cpus = "1"
rayon = "1.10.0"
tokio = { version = "1", features = ["full"] }
clap = {version = "4", features = ["derive"]}
